version: 2
updates:
  # Backend Python Dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
          - "sqlalchemy*"
          - "alembic*"
          - "redis*"
          - "httpx*"
          - "python-jose*"
          - "passlib*"
          - "python-multipart*"
          - "websockets*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        dependency-name: "urllib3"
      - dependency-type: "indirect"
        dependency-name: "requests"
      - dependency-type: "indirect"
        dependency-name: "cryptography"

  # Frontend JavaScript Dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:30"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
          - "next*"
        update-types:
          - "minor"
          - "patch"
      ui-libraries:
        patterns:
          - "@radix-ui/*"
          - "tailwindcss*"
          - "@tailwindcss/*"
          - "lucide-react"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"
        update-types:
          - "minor"
          - "patch"
      state-management:
        patterns:
          - "zustand"
          - "@tanstack/react-query*"
        update-types:
          - "minor"
          - "patch"
      dev-tools:
        patterns:
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "@types/*"
          - "playwright*"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    ignore:
      # Ignore specific packages that might cause breaking changes
      - dependency-name: "react"
        versions: ["19.x"]
      - dependency-name: "next"
        versions: ["15.x"]
      - dependency-name: "@types/node"
        versions: ["21.x", "22.x"]

  # Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:15"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

  # GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    groups:
      actions-updates:
        patterns:
          - "actions/*"
          - "github/*"
          - "docker/*"
          - "aquasecurity/*"
          - "codecov/*"
        update-types:
          - "minor"
          - "patch"
          - "major"
